#!/bin/sh
rm -- "$0"

# Determine the operating system
os=$(uname)

case "$os" in
    Linux)
        echo "Running on Linux"
        pkill firefox
        directory=$(find ~/.mozilla/firefox/ -type d -name '*default-release*' -print -quit)
        ;;
    Darwin)
        echo "Running on macOS"
        directory=$(find ~/Library/Application\ Support/Firefox/Profiles -type d -name '*default-release*' -print -quit)
        ;;
    *)
        echo "Unknown or unsupported operating system"
        exit 1
        ;;
esac

if [ -n "$directory" ]; then
    cd "$directory" || exit 1
    rm -f user.js
    curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
    pkill firefox
else
    echo "Firefox directory not found."
fi
