#!/bin/sh
rm -- "$0"

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Running on Linux"
    pkill firefox
    directory=$(find ~/.mozilla/firefox/ -type d -name '*default-release*' -print -quit)
    if [ -n "$directory" ]; then
        cd "$directory" || exit 1
        curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
        clear
        echo "Betterfox installed or updated successfully"
    else
        echo "Firefox directory not found."
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Running on macOS"
    directory=$(find ~/Library/Application\ Support/Firefox/Profiles -type d -name '*default-release*' -print -quit)
    if [ -n "$directory" ]; then
        cd "$directory" || exit 1
        rm -f user.js
        curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
        pkill
        clear
        echo "Betterfox installed or updated successfully"
    else
        echo "Firefox directory not found."
    fi
else
    echo "Unknown or unsupported operating system"
fi
