#!/bin/sh
rm -- "$0"
directory=$(find ~/Library/Application\ Support/Firefox/Profiles -type d -name '*default-release*' -print -quit)
if [ -n "$directory" ]; then
  cd "$directory" || exit 1
  rm -f user.js
  curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
  pkill firefox
else
  echo "Firefox directory not found."
fi
