#!/bin/sh
rm -- "$0"

# Check if Firefox profile directories exist
if [ -d "$HOME/.mozilla/firefox" ]; then
    echo "Running on Linux"
    pkill firefox
    directory=$(find "$HOME/.mozilla/firefox/" -type d -name '*default-release*' -print -quit)
elif [ -d "$HOME/Library/Application Support/Firefox/Profiles" ]; then
    echo "Running on macOS"
    directory=$(find "$HOME/Library/Application Support/Firefox/Profiles" -type d -name '*default-release*' -print -quit)
else
    echo "Unknown or unsupported operating system"
    exit 1
fi

if [ -n "$directory" ]; then
    cd "$directory" || exit 1
    rm -f user.js
    curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
    pkill firefox
else
    echo "Firefox directory not found."
fi
